apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-auth-server
  labels:
    app: blog-auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-auth-server
  template:
    metadata:
      labels:
        app: blog-auth-server
    spec:
      containers:
        - name: blog-auth-server
          image: piyushdubey1994/blog-auth-server:tagversion
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: blog-auth-server
spec:
  type: LoadBalancer
  selector:
    app: blog-auth-server
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082